before_build:
  - nuget restore
test:
  assemblies:
    only:
      - Bitmex.NET.UnitTests.dll
after_build:
  - nuget pack %APPVEYOR_BUILD_FOLDER%\Bitmex.NET\Bitmex.NET.csproj -Properties Configuration=Release -Build -OutputDirectory %APPVEYOR_BUILD_FOLDER%\Bitmex.NET\bin

artifacts:
  - path: Bitmex.NET\bin\Release
    name: Bitmex.NET_bin
    
  - path: Bitmex.NET\bin\*.nupkg
